### ISSUE TITLE
The live instance at xkcd is dead

### ISSUE THREAD

**Issue by enn-nafnlaus** [xkcd/incredible#3]
Try visiting.

https://xkcd.com/2916/

Not sure if it's a bug or what.

**Comment by marcellourbani** [comment]
https://xkcd.com/2916/api/puzzle returns a 404 from nginx

**Comment by digidietze** [comment]
Yes, balls are stuck in the segments. Only at the bottom there is some animation running (balls flying to jars).

**Comment by enn-nafnlaus** [comment]
Seems to have been resolved.  Glad I opened the ticket  :)
